### ISSUE TITLE
Why do I follow the instructions catkin in the document_ Make DCATKIN_ WHITELIST_ PACKAGES="genmos_object_search_ros did not generate a header file for custom msgs”

### ISSUE THREAD

**Issue by Jm20010201** [zkytony/genmos_object_search#3]
![6b24f75f-ffdf-449e-9915-9a8a303cbb6b](https://github.com/zkytony/genmos_object_search/assets/54173405/2f07a067-b1ca-462f-9980-05978c8a0323)

**Comment by zkytony** [comment]
Based on the log in the screenshot, the messages don't seem to be built. Have you tried removing the `build` folder and rebuild the package?

**Comment by Jm20010201** [comment]
> Based on the log in the screenshot, the messages don't seem to be built. Have you tried removing the `build` folder and rebuild the package?
Thank you for your reply. I have tried deleting the build and devel folders and recompiling, but the result is still the same.

**Comment by zkytony** [comment]
OK, I think this is more like a ROS package building issue. I don't have anything concrete to suggest off the top of my head. I would suggest, try creating a minimum ROS package with a custom message type, and build that package. Then, compare if there is anything different. It's definitely surprising to me that the messages don't get built in your case.

**Comment by Jm20010201** [comment]
> OK, I think this is more like a ROS package building issue. I don't have anything concrete to suggest off the top of my head. I would suggest, try creating a minimum ROS package with a custom message type, and build that package. Then, compare if there is anything different. It's definitely surprising to me that the messages don't get built in your case.

Thank you, the problem was solved after I deleted the file COLCON_IGNORE！
